server:
  port: 8888
  servlet:
    context-path: /ass
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: shiro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
    host: localhost
    database: 0
mybatis-plus:
  mapper-locations: classpath*:/com/example/springbootshiro/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.springbootshiro.mapper : debug
